export const GET_ITEMS = "GET_ITEMS"
export const ADD_ITEM = "ADD_ITEM"
export const EDIT_ITEM = "EDIT_ITEM"
export const DELETE_ITEM = "DELETE_ITEM"
export const CLEAR_TASKS = "CLEAR_TASKS"
export const EDIT_TASK_STATUS = "EDIT_TASK_STATUS"

export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'

export const REFRESH_TOKEN_LOADING = 'REFRESH_TOKEN_LOADING'
export const TOKEN_REFRESH_SUCCESS = 'TOKEN_REFRESH_SUCCESS'